stages:
  - deploy

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region eu-central-1
    - zip -r app.zip .
    - aws s3 cp app.zip s3://code-braudu-bucket/app.zip
    - aws deploy create-deployment --application-name Braudu-Python --deployment-group-name Braudu-Instances --description "New Deployment" --s3-location bucket=code-braudu-bucket,bundleType=zip,key=app.zip
